version: 1
applications:
  - frontend:
      phases:
        preBuild:
          commands: ["npm ci --cache .npm --prefer-offline"]
        build:
          commands:
            - echo "API_ROOT_PORT=$API_ROOT_PORT" >> .env
            - echo "API_ROOT_PROTOCOL=$API_ROOT_PROTOCOL" >> .env
            - echo "API_ROOT_URL=$API_ROOT_URL" >> .env
            - npm run build
      artifacts:
        baseDirectory: .next
        files:
          - "**/*"
      cache:
        paths:
          - ".next/cache/**/*"
          - ".npm/**/*"
    appRoot: frontend
